=head1 ABOUT

A OO Perl interface to the Steam community data L<https://partner.steamgames.com/documentation/community_data>

=head1 USAGE

	use WebService::Steam::User;

	my $user = WebService::Steam::User->get( nick => 'jraspass' );

=head1 AUTHOR

James Raspass, E<lt>jraspass@gmail.comE<gt>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
